### ISSUE TITLE
How can this libray be used on a local network with many machines

### ISSUE THREAD

**Issue by l16h7n1n6s** [ep2p/kademlia-api#19]
Can this library be used in local p2p network with many machines or its only working and tested on the same machine. if yes can you give an example?

**Comment by sepehr-gh** [comment]
I am sorry for the late reply

The networking layer of the library is abstract and should be implemented by the developer of the project that uses this library.
I think your question mostly goes there.

For testing purposes, there is no "networking layer" implemented. However, you can try having HTTP server and client on your nodes to send and receive requests, so it can both work in a local machine and in any network as well.

**Comment by sepgh** [comment]
Implementing [Kademlia Netty](https://github.com/ep2p/kademlia-netty) with networking example.

**Comment by l16h7n1n6s** [comment]
@sepgh The link you provide is not active can you please change it and give some directions how to implement the networking logic

**Comment by sepgh** [comment]
True, I made it public.

I should mention again that it's just under implementation and needs some more time. I'm working on using netty as client/server and gson for serializing network requests.

**Comment by l16h7n1n6s** [comment]
@sepgh perfect please when you ready update the readme.md file and include some examples of how to use it

**Comment by sepgh** [comment]
The work on [kademlia-netty](https://github.com/ep2p/kademlia-netty) has improved enough so that I can announce it here.

You can take a look at the examples and [check the code](https://github.com/ep2p/kademlia-netty/blob/main/src/test/java/io/ep2p/kademlia/netty/Example.java) at this stage. Of course there is a lot more to develop and improve but I suppose it will give the basic understanding on how to use this API. Will be improving the documentation and examples with any new version.

P.S: it's not on maven central yet.

I am closing this issue. Feel free to create new ones there or here depending on the subject.
Thanks a lot.

**Comment by sepgh** [comment]
For anyone reading this, an example is added here:

https://github.com/ep2p/kademlia-netty-standalone-test
