### ISSUE TITLE
NAT traversal with holepunching technique

### ISSUE THREAD

**Issue by nishp77** [ep2p/kademlia-api#49]
Hi @sepgh I'm very new to P2P understanding it, I found my way here from Hypercore Protocol (https://docs.holepunch.to/). Since there's no network implementation it our responsibility for implementing the NAT traversal? 

I  looked at the netty example, is it that once a connection is made we're communicating in REST API? It's example so we could have anything there on the network layer?

**Comment by nishp77** [comment]
I'm not a expert on P2P but I'm trying to build as Delivery platform, so I would like to ask you if there's a benefit on communicating via HTTP or could we use streams to pass encoded json/ proto buffers?

**Comment by sepgh** [comment]
Good day,

The reason there is a high level abstraction on networking layer is exactly such problems as mentioned. Not everyone needs their p2p system to work behind NAT enabled routers.

If that's what you need then indeed you'd need to consider using libraries such as [this one](https://github.com/offbynull/portmapper) or a holepunching techniques. I'm not a p2p expert either but since AFAIK you'd need an intermediate server for holepunching you should consider how your network is decentralised (just something to mind)

Kademlia-netty is HTTP implementation of the networking layer, that's right. The main benefit was ease of understanding and implementation (although there is space for improvements), connection reusing (connection pool) and TCP benefits over the usual implementation suggestions where UDP is preferred (for better performance but it's less reliable and harder to implement).

But of course you can implement your networking layer with proto buffers. There is already an abstraction and gson implementation for json serialisation which you can use and extend.


Let me know what else I can help with.

**Comment by sepgh** [comment]
This is a good question and you should feel free to elaborate more, however due to inactivity I'm closing this issue.
